### ISSUE TITLE
Impossible to get the pedestrian crossings on the map

### ISSUE THREAD

**Issue by dx6nxr** [BerkeleyLearnVerify/Scenic#281]
### System Details

1. Python ver.: 3.8.10
2. Scenic ver.: 3.0.0b2
3. OS: Intel / Win 11
4. Simulation in carla

### Detailed Description

1. When trying to extract all of the pedestrian crossings on the map, none are returned, doesn't matter if I try to get them from the intersections or the roads. I.e. if I try to get all the roads where crossings are not an empty tuple, `roads = filter(lambda i: i.crossings != (), network.roads)`, and assert that list is not empty, I get the assertionError. Code is as follows: 
```
param map = 'assets/maps/CARLA/Town05.xodr'
param carla_map = 'Town05'
param time_step = 1.0/10

model scenic.simulators.carla.model

roads = filter(lambda i: i.crossings != (), network.roads)

assert len(roads) > 0, \
    'No roads with crossings found in the network'
```
2. `scenic -S --2d  --count 1 ..\ScenicToOSC\scenic\scenarioUnexpectedPedestrianOnIntersection.scenic -b`
3. ```
Beginning scenario construction...
pygame 2.5.2 (SDL 2.28.3, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
  Loading cached version of road network...
  Loaded cached network in 0.36 seconds.
Traceback (most recent call last):
  File "C:\Users\ivbu01\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ivbu01\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\venv1\Scripts\scenic.exe\__main__.py", line 4, in <module>
    from scenic.__main__ import dummy
  File "C:\Scenic\src\scenic\__main__.py", line 195, in <module>
    scenario = errors.callBeginningScenicTrace(
  File "C:\Scenic\src\scenic\core\errors.py", line 282, in callBeginningScenicTrace
    return func()
  File "C:\Scenic\src\scenic\__main__.py", line 196, in <lambda>
    lambda: translator.scenarioFromFile(
  File "C:\Scenic\src\scenic\syntax\translator.py", line 142, in scenarioFromFile
    return _scenarioFromStream(
  File "C:\Scenic\src\scenic\syntax\translator.py", line 172, in _scenarioFromStream
    compileStream(stream, namespace, compileOptions, filename)
  File "C:\Scenic\src\scenic\syntax\translator.py", line 321, in compileStream
    executeCodeIn(code, namespace)
  File "C:\Scenic\src\scenic\syntax\translator.py", line 560, in executeCodeIn
    exec(code, namespace)
  File "C:\ScenicToOSC\scenic\scenarioUnexpectedPedestrianOnIntersection.scenic", line 12, in <module>
    assert len(roads) > 0, \
AssertionError: No roads with crossings found in the network
```

### Steps To Reproduce

1. Just running the code on any map is enough to reproduce the problem.
```
param map = 'assets/maps/CARLA/Town05.xodr'
param carla_map = 'Town05'
param time_step = 1.0/10

model scenic.simulators.carla.model

roads = filter(lambda i: i.crossings != (), network.roads)

assert len(roads) > 0, \
    'No roads with crossings found in the network'
```

### Issue Submission Checklist

- [X] I am reporting an issue, not asking a question
- [X] I checked the open and closed issues, forum, etc. and have not found any solution
- [X] I have provided all necessary code, etc. to reproduce the issue

**Comment by dx6nxr** [comment]
I dig into the code a bit, and found out that crossings are only initialized to `()` in the Road class when initializing the road itself, and never added after, thus no wonder this doesn't work.
 `crossings: Tuple[PedestrianCrossing] = ()` from scenic/domain/driving/roads.py line 431.

**Comment by dfremont** [comment]
Hi Ivan, you're right, our OpenDRIVE parser currently does not extract information about pedestrian crossings (OpenDRIVE objects of type "crosswalk"). If you want to try implementing that functionality, we'd be happy to advise (you can make a post on our new [forum](https://forum.scenic-lang.org/) if you like); otherwise, it's not a priority for us at the moment but we can try to take a look some time this year.

**Comment by dfremont** [comment]
The cached maps are saved in `.snet` files next to the original `.xodr` files. You can also add the line `param map_options = {"useCache": False}` to your Scenic program to disable reading the cached versions automatically.

**Comment by dx6nxr** [comment]
Thank you!

**Comment by dx6nxr** [comment]
Hey,
Just wanted to share what I was able to do and ask a question considering the positioning of the crosswalks. On the image one can see that crosswalk's geometry is being parsed (in green), but I cannot figure out how do I give them the correct position. As crosswalk is of a type NetworkElement, i guess I should somehow give it orientation when initializing it, but I am confused as whether it is the correct solution, and if it is, then what .xodr paramaters do u use for orientation. Thanks! 

![image](https://github.com/user-attachments/assets/9053a8c9-5dc8-4cf1-b700-0ae6dd6c065c)

**Comment by dfremont** [comment]
The `orientation` attribute of `NetworkElement` isn't the orientation of the element itself: it's a vector field giving a preferred orientation to objects placed in the region (lanes for example have a preferred orientation which is given by the direction of traffic). You could simply ignore the `orientation` attribute to start with.

The position of the crosswalk is given by its `polygon` property, which should be a Shapely `Polygon` or `MultiPolygon`. I haven't looked to see how crosswalks are represented in OpenDRIVE, but you'll need to extract global XY coordinates for the vertices of the crosswalk and build a `Polygon` from that. In `xodr_parser.py` we have code which does this for roads, lanes, sidewalks, etc. starting from their reference line and width data in an OpenDRIVE file (mainly `Road.calc_geometry_for_type`; the resulting polygons are used in `Road.toScenicRoad` to create Scenic `Lane`, `LaneSection`, `Sidewalk`, etc. objects). You might be able to adapt that code, although the documentation is minimal.

**Comment by dx6nxr** [comment]
I have a bit of an issue with the heading, as I'm taking the heading angle of the curve at which the crossing is located, some of the crossings are looking weird. Maybe there is a hidden function like "point_at" but for heading? If not, will be a good alternative to add such function to each geometry type in xodr_parser.py? Hope for a quick answer :)

![image](https://github.com/user-attachments/assets/021f2857-a839-4b34-96af-161e4f754e41)

Best, Ivan
