### ISSUE TITLE
Test dangling specifier lists fails

### ISSUE THREAD

**Issue by sjunges** [BerkeleyLearnVerify/Scenic#3]
Hi, 

this is to let you know that one test fails for me.
In particular, upon executing pytest on the tests folder,
I obtain:

```bash
pytest tests      
====================================== test session starts ======================================
platform darwin -- Python 3.7.0, pytest-5.4.0, py-1.8.1, pluggy-0.13.1
rootdir: /Users/sjunges/cal/Scenic
collected 428 items / 2 skipped / 426 selected  
(.....)
=========================================== FAILURES ============================================
_________________________________ test_dangling_specifier_list __________________________________

    def test_dangling_specifier_list():
        with pytest.raises(TokenParseError):
>           compileScenic('ego = Object with width 4,')
E           Failed: DID NOT RAISE <class 'scenic.syntax.translator.TokenParseError'>

tests/syntax/test_tokenization.py:43: Failed
------------------------------------- Captured stdout call --------------------------------------
  Pruning scenario...
  Pruned scenario in 1.073e-05 seconds.
==================================== short test summary info ====================================
FAILED tests/syntax/test_tokenization.py::test_dangling_specifier_list - Failed: DID NOT RAISE...
===================== 1 failed, 427 passed, 2 skipped in 100.47s (0:01:40)
```

**Comment by dfremont** [comment]
Hmm, the test works for me in Python 3.7.2. Can you please make a file _test.sc_ containing the single line `ego = Object with width 4,` (note the comma at the end), confirm that running `python -m scenic test.sc` does not give a parse error, and then send me the output of `python -m tokenize test.sc`? Thanks!

**Comment by sjunges** [comment]
Here is the output when running this test.sc with a *single* line:
```
python -m scenic test.sc
Beginning scenario construction...
  Pruning scenario...
  Pruned scenario in 9.775e-06 seconds.
Scenario constructed in 0.02 seconds.
```

Tokenize gives:

```
0,0-0,0:            ENCODING       'utf-8'        
1,0-1,3:            NAME           'ego'          
1,4-1,5:            OP             '='            
1,6-1,12:           NAME           'Object'       
1,13-1,17:          NAME           'with'         
1,18-1,23:          NAME           'width'        
1,24-1,25:          NUMBER         '4'            
1,25-1,26:          OP             ','            
2,0-2,0:            ENDMARKER      ''      
```

And here is the output when running it with an additional empty line:
```
Beginning scenario construction...
Traceback (most recent call last):
  File "/Users/sjunges/.pyenv/versions/3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/sjunges/.pyenv/versions/3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sjunges/.pyenv/versions/scenic/lib/python3.7/site-packages/scenic-1.0.0b2-py3.7.egg/scenic/__main__.py", line 52, in <module>
    scenario = translator.scenarioFromFile(args.scenario)
  File "/Users/sjunges/.pyenv/versions/scenic/lib/python3.7/site-packages/scenic-1.0.0b2-py3.7.egg/scenic/syntax/translator.py", line 81, in scenarioFromFile
    return scenarioFromStream(stream, filename=fullpath, path=path)
  File "/Users/sjunges/.pyenv/versions/scenic/lib/python3.7/site-packages/scenic-1.0.0b2-py3.7.egg/scenic/syntax/translator.py", line 87, in scenarioFromStream
    compileStream(stream, namespace, filename=filename)
  File "/Users/sjunges/.pyenv/versions/scenic/lib/python3.7/site-packages/scenic-1.0.0b2-py3.7.egg/scenic/syntax/translator.py", line 145, in compileStream
    newSource, lineMap, allConstructors = translator.translate(block)
  File "/Users/sjunges/.pyenv/versions/scenic/lib/python3.7/site-packages/scenic-1.0.0b2-py3.7.egg/scenic/syntax/translator.py", line 711, in translate
    'expected indented specifier (extra comma on previous line?)')
scenic.syntax.translator.TokenParseError: Parse error in line 2: expected indented specifier (extra comma on previous line?)
```

P.S. I should definitively update that environment to python 3.7.2 once this issue is resolved.

**Comment by dfremont** [comment]
Bizarre: all versions of Python I have (3.6.8, 3.7.2, 3.8.0) consistently tokenize that source differently, adding a `NEWLINE` token after the `OP` for the comma.

_Later:_ Aha, it seems this [change](https://bugs.python.org/issue33899) made in 3.8 was backported to 3.6 and 3.7, explaining how it can occur in your 3.7.0 but not in my 3.6.8 or 3.7.2.

Anyway, I've handled this case and added a test for it - thanks!
