### ISSUE TITLE
Error using CARLA as simulator: the "carla" package is required to run simulation

### ISSUE THREAD

**Issue by dbarrita** [BerkeleyLearnVerify/Scenic#317]
### System Details

Python Python 3.10.12
Scenic 3.0.0
Ubuntu 22.04
CARLA 0.9.13 (binary)

### Detailed Description

I'm trying to launch scenic with CARLA in several scenes, but it doesn't work. For example with the following command:
$ scenic --2d Carla_Challenge/carlaChallenge1.scenic --simulate --model scenic.simulators.carla.model -b

I received the following error:
  _Beginning scenario construction...
    Loading cached version of road network...
    Loaded cached network in 0.07 seconds.
  /home/usuario/source/external/Scenic/src/scenic/simulators/carla/model.scenic:60: SimulatorInterfaceWarning: the "carla" package is not installed; will not be able to run dynamic simulations
    warnings.warn('the "carla" package is not installed; '
    Pruning scenario...
    Pruned scenario in 1.383e-05 seconds.
  Scenario constructed in 0.50 seconds.
  Traceback (most recent call last):
    File "/home/usuario/PythonEnv/venvscenic/bin/scenic", line 5, in <module>
      from scenic.__main__ import dummy
    File "/home/usuario/source/external/Scenic/src/scenic/__main__.py", line 209, in <module>
      simulator = errors.callBeginningScenicTrace(scenario.getSimulator)
    File "/home/usuario/source/external/Scenic/src/scenic/core/errors.py", line 282, in callBeginningScenicTrace
      return func()
    File "/home/usuario/source/external/Scenic/src/scenic/core/scenarios.py", line 661, in getSimulator
      return veneer.instantiateSimulator(self.simulator, self.params)
    File "/home/usuario/source/external/Scenic/src/scenic/syntax/veneer.py", line 465, in instantiateSimulator
      return factory()
    File "/home/usuario/source/external/Scenic/src/scenic/simulators/carla/model.scenic", line 103, in <lambda>
      simulator CarlaSimulator(
    File "/home/usuario/source/external/Scenic/src/scenic/simulators/carla/model.scenic", line 69, in CarlaSimulator
      raise RuntimeError('the "carla" package is required to run simulations '
  RuntimeError: the "carla" package is required to run simulations from this scenario_

If I use the command:
$ pip show CARLA

The output is this:
_Name: carla
Version: 0.9.13
Summary: Python API for communicating with the CARLA server.
Home-page: https://github.com/carla-simulator/carla
Author: The CARLA team
Author-email: carla.simulator@gmail.com
License: MIT License
Location: /home/usuario/.local/lib/python3.10/site-packages
Requires: 
Required-by: #N/A_

The scene runs with the Newtonian simulator. Also I can use CARLA separately from Scenic without problem.

### Steps To Reproduce

With a device with the same system details run a scene using CARLA, for example:
$ scenic --2d Carla_Challenge/carlaChallenge1.scenic --simulate --model scenic.simulators.carla.model -b

### Issue Submission Checklist

- [X] I am reporting an issue, not asking a question
- [X] I checked the open and closed issues, forum, etc. and have not found any solution
- [X] I have provided all necessary code, etc. to reproduce the issue

**Comment by Eric-Vin** [comment]
Apologies for the delay in responding to this. If you're still experiencing this issue, could you please provide the output of `pip freeze`?
